"""Generate the frontend catalogue from the shared backend source."""

import argparse
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    messages = json.loads(
        (root / "backend/locales/en.json").read_text(encoding="utf-8")
    )
    content = (
        "// Generated by scripts/generate_locales.py; edit backend/locales/en.json.\n// prettier-ignore\nexport default "
        + json.dumps(messages, ensure_ascii=False, indent=2)
        + ";\n"
    )
    target = root / "src/locales.ts"
    if args.check:
        if target.read_text(encoding="utf-8") != content:
            raise SystemExit(
                "Catalogue is stale; run python scripts/generate_locales.py"
            )
    else:
        target.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
